name: liberty_printer
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  blue_thermal_printer: ^1.2.0
  libertymodel:
    git: https://github.com/qrcode-protect/libertymodel.git
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_login_package:
    git: https://github.com/qrcode-protect/firebase_login_package.git
  firebase_storage: ^10.2.6
  cloud_firestore: ^3.1.7
  flutter_star_prnt: ^2.3.6
  qr_flutter: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/